<?= $this->extend('web/components/assemble') ?>

<?= $this->section('content') ?>

<main class="__className_7bc5c9">
    <div class="bg-[#dde7f2] lg:py-12 md:py-10 py-8">
        <h1 class="text-center lg:text-5xl md:text-4xl text-3xl text-heading font-black">Terms of Service</h1>
    </div>

    <div class="container my-6">
        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">General</h2>
        <p class="text-base text-para mb-4 font-semibold">
            Welcome to <strong>DoctorBano.com</strong>. By accessing or using this website, mobile application, or any services offered by
            <strong>Essqube Enterprises LLP</strong> (“<strong>DoctorBano</strong>”, “we”, “us”), you agree to these Terms of Service along with our Privacy Policy.
            The term “you” refers to the user/visitor of our platform. This agreement is an electronic record generated by a computer system; no physical or digital signatures are required.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Our Guidelines</h2>
        <ul class="list-disc pl-7">
            <li class="text-base text-para font-semibold mb-3">Content is provided for general information and may change without prior notice.</li>
            <li class="text-base text-para font-semibold mb-3">We do not warrant the accuracy, timeliness, performance, completeness or suitability of information and materials provided. You acknowledge content may contain inaccuracies and we disclaim liability to the fullest extent permitted by law.</li>
            <li class="text-base text-para font-semibold mb-3">Your use of any information or materials is at your own risk. You are responsible for ensuring our services meet your requirements.</li>
            <li class="text-base text-para font-semibold mb-3">All materials, branding, and content are owned by or licensed to DoctorBano. Reproduction or redistribution is prohibited unless expressly permitted.</li>
            <li class="text-base text-para font-semibold mb-3">Unauthorised use may give rise to a claim for damages and/or be a criminal offence.</li>
            <li class="text-base text-para font-semibold mb-3">Our platform may link to third-party websites for convenience. Links do not signify endorsement; we are not responsible for their content, privacy, or practices.</li>
            <li class="text-base text-para font-semibold mb-3">You may not create a link to this website without our prior written consent.</li>
            <li class="text-base text-para font-semibold mb-3">Your use of this platform is subject to applicable laws of India and other regulatory authorities as relevant.</li>
        </ul>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Scope of Services & Limitations</h2>
        <ul class="list-disc pl-7">
            <li class="text-base text-para font-semibold mb-3">We provide counselling for MBBS/medical education abroad, including profile evaluation, university shortlisting, application assistance, documentation guidance, visa guidance, and pre-departure support.</li>
            <li class="text-base text-para font-semibold mb-3"><strong>No Guarantee:</strong> Admission decisions, seat availability, fees, visa outcomes, immigration rules, and university policies are controlled by third parties. DoctorBano does not guarantee admission, scholarships, or visa approval.</li>
            <li class="text-base text-para font-semibold mb-3">All timelines are indicative and may vary depending on third-party processing.</li>
        </ul>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Personal Use and Restrictions</h2>
        <p class="text-base text-para mb-4 font-semibold">Use our services for personal, non-commercial purposes only. You agree that:</p>
        <ul class="list-disc pl-7">
            <li class="text-base text-para font-semibold mb-3">You will not rely on site content as professional, legal, immigration, or tax advice.</li>
            <li class="text-base text-para font-semibold mb-3">You will not decompile, reverse engineer, or disassemble any part of the platform.</li>
            <li class="text-base text-para font-semibold mb-3">You will not use our platform/services for unlawful purposes, unsolicited advertising, or infringing activities.</li>
            <li class="text-base text-para font-semibold mb-3">Compatibility with all devices/browsers is not guaranteed.</li>
            <li class="text-base text-para font-semibold mb-3">We are not responsible for any loss or damage to hardware/software arising from use of the platform.</li>
            <li class="text-base text-para font-semibold mb-3">To the maximum extent permitted by law, DoctorBano shall not be liable for indirect, incidental, special, exemplary, or consequential damages arising from use or misuse of the platform or services.</li>
            <li class="text-base text-para font-semibold mb-3">We may contact you via SMS, WhatsApp, email, or phone for service/transactional updates. By providing your number/email, you consent to such communications even if listed on DND registries.</li>
            <li class="text-base text-para font-semibold mb-3">You agree to indemnify and hold DoctorBano, its partners, directors, employees, agents and representatives harmless from claims, losses, liabilities, and costs arising from your breach of these Terms or misuse of the platform.</li>
            <li class="text-base text-para font-semibold mb-3">Services require your cooperation and accurate documentation. If you fail to provide required, genuine information/documents or do not complete agreed steps, services/subscriptions may be terminated without refund.</li>
        </ul>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Fees, Payments & Refunds</h2>
        <ul class="list-disc pl-7">
            <li class="text-base text-para font-semibold mb-3">Applicable counselling/service fees, government fees, university fees, visa charges, insurance, travel, and other third-party charges are borne by you.</li>
            <li class="text-base text-para font-semibold mb-3">Unless stated otherwise in a written service agreement, fees paid to DoctorBano for counselling/services are <strong>non-refundable</strong> once the service is initiated.</li>
            <li class="text-base text-para font-semibold mb-3">Payments are processed through secure gateways; DoctorBano does not store full card details on its servers.</li>
        </ul>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Age Eligibility</h2>
        <p class="text-base text-para mb-4 font-semibold">
            If you are below 18 years (or the age of majority under applicable law), you may use our services only with the involvement and consent of a parent or legal guardian. You warrant that the information you provide is accurate and complete.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Privacy Policy</h2>
        <p class="text-base text-para mb-4 font-semibold">
            We respect your privacy. Please review our Privacy Policy to understand how we collect, use, and share your information. By using our services, you consent to our data practices.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Intellectual Property</h2>
        <p class="text-base text-para mb-4 font-semibold">
            All logos, trademarks, graphics, text, and software on the platform are the property of DoctorBano or its licensors. No licence is granted except as necessary for personal use of the site in accordance with these Terms.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Force Majeure</h2>
        <p class="text-base text-para mb-4 font-semibold">
            We shall not be liable for any delay or failure to perform due to events beyond our reasonable control, including acts of God, government actions, war, strikes, pandemics, network failures, or third-party service disruptions.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Term and Termination</h2>
        <p class="text-base text-para mb-4 font-semibold">
            These Terms remain in effect unless terminated by you or us. We may suspend or terminate access for breach of these Terms or our Privacy Policy, or for misuse of the platform. Upon termination, your right to use the services ceases immediately.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Governing Law & Jurisdiction</h2>
        <p class="text-base text-para mb-4 font-semibold">
            These Terms are governed by the laws of India. The courts at <strong>New Delhi, India</strong> shall have exclusive jurisdiction over disputes arising out of or in connection with these Terms or your use of the platform. We may, at our discretion, initiate proceedings in your jurisdiction of residence or use.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Changes to These Terms</h2>
        <p class="text-base text-para mb-4 font-semibold">
            We may update these Terms from time to time. Continued use after changes constitutes acceptance of the revised Terms.
        </p>

        <h2 class="md:text-2xl text-xl text-heading font-bold md:mt-6 mt-4 mb-2">Contact Us</h2>
        <p class="text-base text-para mb-1 font-semibold"><strong>DoctorBano.com / Essqube Enterprises LLP</strong></p>
        <p class="text-base text-para mb-1 font-semibold">A-23, Connaught Place, New Delhi – 110001, India</p>
        <p class="text-base text-para mb-1 font-semibold">Liaison Office: No.11, Str6, Ordzhonikidze Street, 115419, Moscow, Russia</p>
        <p class="text-base text-para mb-1 font-semibold">Phone: +91-8447730303 / +91-8447630303</p>
        <p class="text-base text-para mb-4 font-semibold">
            Email: <a class="underline text-[#066ac9]" href="mailto:info@doctorbano.com">info@doctorbano.com</a>
            <?php /* Optional alternate: | <a class="underline text-[#066ac9]" href="mailto:essqubellp@gmail.com">essqubellp@gmail.com</a> */ ?>
        </p>

        <p class="text-sm text-para mb-2">
            <em>Disclaimer:</em> This page provides general terms for typical counselling services. It is not legal advice. For compliance-critical use (e.g., DPDP Act grievance officer line), please consult your counsel.
        </p>
    </div>
</main>

<?= $this->endSection(); ?>